### PR TITLE
Switch to Github Actions

### LINKED ISSUE #25: Switch to Github Actions CI
Due to the shutdown of travis-ci.org, all existing pipelines will be dead soon, so it makes sense to switch to Github Actions, which will remain free for OS projects.

### PR DESCRIPTION
**Pull request by danirukun**
Closes #25 

Added Github Actions build and test workflow for different Elixir and OTP version combinations.

### CODE REVIEW

**Comment by danirukun** [comment]
@sheharyarn please review, thanks.

**Comment by sheharyarn** [comment]
This is amazing, @DaniruKun! Thank you!

**Comment by danirukun** [comment]
@sheharyarn it was open for a while, during that time the original Elixir action was migrated to Erlef and turned into a generic Beam one: https://github.com/erlef/setup-beam

You can switch to it yourself or I'll make another MR on the weekend.

**Comment by sheharyarn** [comment]
Already on it, thanks!

**Pull request merged**
